### PR TITLE
Debug Code Editor: Try to execute a method named main first

### PR DESCRIPTION
**Pull request by MrFusion42**
When executing code in the `_debug/code` tool, the method being executed is very random if there's more than one static method with no parameters (even if only one of them is public!).

This PR tries first to execute a method named `main`, otherwise a random one is executed (as before).

### CODE REVIEW

**Comment by MrFusion42** [comment]
Looks like the Travis CI build failed because of a network error

**Comment by gitastrophe** [comment]
I restarted it for you.

**Comment by MrFusion42** [comment]
@gitastrophe It's still failing, but it still doesn't seem to be related with my changes:
```
[ERROR]   The project com.psddev:dari-reflections:3.2-SNAPSHOT
  (/home/travis/build/perfectsense/dari/reflections/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: 
  Could not transfer artifact com.psddev:dari:pom:3.2-SNAPSHOT from/to codehaus-snapshots
  (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org and 'parent.relativePath' points
  at wrong local POM @ line 9, column 13: Unknown host nexus.codehaus.org -> [Help 2]
```

**Comment by danslaughter2** [comment]
@MrFusion42 I think the issue is actually due to the target branch of the pull request being master. Can you close this and reopen it against perfectsense:release/3.2 ?

**Comment by MrFusion42** [comment]
Sure, will do 👍

**Pull request closed without merging**
