### PR TITLE
Debug Code Editor: Try to execute a method named main first

### PR DESCRIPTION
**Pull request by MrFusion42**
When executing code in the `_debug/code` tool, the method being executed is very random if there's more than one static method with no parameters (even if only one of them is public!).

This PR tries first to execute a method named `main`, otherwise a random one is executed (as before).

### CODE REVIEW

**Comment by MrFusion42** [comment]
@danslaughter2 Ready

**Comment by MrFusion42** [comment]
Good grief...  The build failed again

**Comment by danslaughter2** [comment]
@MrFusion42 Checkstyle errors. Compile your code with `mvn -Plibrary verify` before submitting to verify those issues are addressed.

**Comment by MrFusion42** [comment]
Cool, didn't know you had stylecheck

**Pull request merged**
